import { Router } from 'express';
import authRoutes from './auth.routes.js';
import meRoutes from './me.routes.js';
import usersRoutes from './users.routes.js';
import stationsRoutes from './stations.routes.js';
import slotsRoutes from './slots.routes.js';
import assignmentsRoutes from './assignments.routes.js';
import vehiclesRoutes from './vehicles.routes.js';
import invoicesRoutes from './invoices.routes.js';
import transactionsRoutes from './transactions.routes.js';
import logsRoutes from './logs.routes.js';
import settingsRoutes from './settings.routes.js';
import notificationsRoutes from './notifications.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import searchRoutes from './search.routes.js';
import healthRoutes from './health.routes.js';
import myWalletRoutes from './my-wallet.routes.js';
import mySessionsRoutes from './my-sessions.routes.js';
import myFinancesRoutes from './my-finances.routes.js';
import myPaymentMethodsRoutes from './my-payment-methods.routes.js';
import myVehiclesRoutes from './my-vehicles.routes.js';
import financesRoutes from './finances.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/me/wallet', myWalletRoutes);
apiRouter.use('/me/sessions', mySessionsRoutes);
apiRouter.use('/me/finances/payment-methods', myPaymentMethodsRoutes);
apiRouter.use('/me/finances', myFinancesRoutes);
apiRouter.use('/me/vehicles', myVehiclesRoutes);
apiRouter.use('/finances', financesRoutes);
apiRouter.use('/me', meRoutes);
apiRouter.use('/users', usersRoutes);
apiRouter.use('/stations', stationsRoutes);
apiRouter.use('/slots', slotsRoutes);
apiRouter.use('/assignments', assignmentsRoutes);
apiRouter.use('/vehicles', vehiclesRoutes);
apiRouter.use('/invoices', invoicesRoutes);
apiRouter.use('/transactions', transactionsRoutes);
apiRouter.use('/logs', logsRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/notifications', notificationsRoutes);
apiRouter.use('/dashboard', dashboardRoutes);
apiRouter.use('/search', searchRoutes);
apiRouter.use('/health', healthRoutes);
